backend:
  name: git-gateway
  repo: martusheff/oakridgeinteriors
  branch: main
  identity_url: https://auth.decapbridge.com/sites/3a6b8f3b-499e-4868-a881-707bd250ed4d
  gateway_url: https://gateway.decapbridge.com

commit_messages:
  create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
  delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge 
  uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
  openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

editor:
  preview: false

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/page/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero", widget: "image" }
          - { label: "Hero Background Image", name: "herobackground", widget: "image" }
          - { label: "CTA Label", name: "herocta", widget: "string" }
          - { label: "CTA URL", name: "heroctaurl", widget: "string" }
      - file: "content/page/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero", widget: "image" }
          - { label: "Hero Background Image", name: "herobackground", widget: "image" }
          - { label: "CTA Label", name: "herocta", widget: "string" }
          - { label: "CTA URL", name: "heroctaurl", widget: "string" }
      - file: "content/page/reviews.md"
        label: "Reviews Page"
        name: "reviews"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero", widget: "image" }
          - { label: "Hero Background Image", name: "herobackground", widget: "image" }
          - { label: "CTA Label", name: "herocta", widget: "string" }
          - { label: "CTA URL", name: "heroctaurl", widget: "string" }
      - file: "content/page/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero", widget: "image" }
          - { label: "Hero Background Image", name: "herobackground", widget: "image" }
          - { label: "CTA Label", name: "herocta", widget: "string" }
          - { label: "CTA URL", name: "heroctaurl", widget: "string" }
      - file: "content/page/gallery.md"
        label: "Gallery Page"
        name: "gallery"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Background Image", name: "herobackground", widget: "image" }
          - label: "Gallery"
            name: "images"
            widget: "list"
            fields:
              - { label: Image, name: image, widget: image }

              
  - name: "config"
    label: "Config"
    files:
      - file: "content/config/website.json"
        label: "Site Config"
        name: "website"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }