backend:
  name: git-gateway
  repo: martusheff/oakridgeinteriors
  branch: main
  identity_url: https://auth.decapbridge.com/sites/3a6b8f3b-499e-4868-a881-707bd250ed4d
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge
editor:
  preview: false
media_folder: "public/images/uploads" # Where images are stored
public_folder: "/images/uploads" # Public path for images


collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "Hero Background Image", name: "heroBackgroundImage", widget: "image" }
          - { label: "CTA Label", name: "ctaLabel", widget: "string" }
          - { label: "CTA URL", name: "ctaUrl", widget: "string" }
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "Hero Background Image", name: "heroBackgroundImage", widget: "image" }
          - { label: "CTA Label", name: "ctaLabel", widget: "string" }
          - { label: "CTA URL", name: "ctaUrl", widget: "string" }