backend:
  name: git-gateway
  repo: martusheff/oakridgeinteriors
  branch: main
  identity_url: https://auth.decapbridge.com/sites/3a6b8f3b-499e-4868-a881-707bd250ed4d
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge
editor:
  preview: false
media_folder: "public/images/uploads" # Where images are stored
public_folder: "/images/uploads" # Public path for images
collections:
  - name: 'page'
    label: 'Pages'
    files:
      - file: 'content/page/home.md'
        label: 'Home'
        name: 'home'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Hero Image', name: 'heroimage', widget: 'image', choose_url: false }
          - { label: 'Hero Background Image', name: 'herobackgroundimage', widget: 'image', choose_url: false }
          - { label: 'Hero CTA Label', name: 'heroctalabel', widget: 'string' }
          - { label: 'Hero CTA URL', name: 'heroctaurl', widget: 'string' }

  - name: "posts"
    label: "Posts"
    folder: "content/posts" # Folder for @nuxt/content
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
